# Generated by Django 3.1.2 on 2020-11-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MateriasPrimas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Humedad', models.IntegerField()),
                ('Proteina', models.IntegerField()),
                ('Grasa', models.IntegerField()),
            ],
        ),
    ]
