# Generated by Django 3.1.2 on 2021-01-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBMysql', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiasprimas',
            name='Cenizas',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='materiasprimas',
            name='Fibra',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='materiasprimas',
            name='Grasa',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='materiasprimas',
            name='Humedad',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='materiasprimas',
            name='Proteina',
            field=models.FloatField(),
        ),
    ]
