# Generated by Django 3.1.2 on 2020-11-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='Correo',
            field=models.EmailField(max_length=25),
        ),
    ]
